from dotenv import load_dotenv
import os

load_dotenv()

DISCORD_WEBHOOK = os.getenv("DISCORD_WEBHOOK")
JUMBO_DISCORD_WEBHOOK = os.getenv("JUMBO_DISCORD_WEBHOOK")
CRUZVERDE_DISCORD_WEBHOOK = os.getenv("CRUZVERDE_DISCORD_WEBHOOK")
FARMATODO_DISCORD_WEBHOOK = os.getenv("FARMATODO_DISCORD_WEBHOOK")
MAKRO_DISCORD_WEBHOOK = os.getenv("MAKRO_DISCORD_WEBHOOK")
LAREBAJA_DISCORD_WEBHOOK = os.getenv("LAREBAJA_DISCORD_WEBHOOK")

ERRORS_DISCORD_WEBHOOK = os.getenv("ERRORS_DISCORD_WEBHOOK")